### ISSUE TITLE
Tooling integration support?

### ISSUE THREAD

**Issue by aadrian** [themesberg/volt-bootstrap-5-dashboard#10]
Hi,

Any plans offering some sort of minimal tooling integration support? ( for some popular ones like https://bootstrapstudio.io ? )

E.g. for BootstrapStudio this would resume to offering the components and snippets also as `.bscomp` files, and just document how to import the Volt theme.

Thank you.

**Comment by zoltanszogyenyi** [comment]
Hello @aadrian,

We can definitely consider it towards the end of the year.
