### ISSUE TITLE
Bug with mobile navbar selection

### ISSUE THREAD

**Issue by jashsayani** [themesberg/volt-bootstrap-5-dashboard#11]
I was just looking at the theme in different modes (desktop, mobile, etc) and noticed a bug:

<img width="350" alt="Screen Shot 2020-09-05 at 6 56 25 PM" src="https://user-images.githubusercontent.com/18684/92316495-b8f81900-efa9-11ea-8e2d-e62fd0e502df.png">

Closeup:

<img width="831" alt="Screen Shot 2020-09-05 at 6 57 18 PM" src="https://user-images.githubusercontent.com/18684/92316498-beedfa00-efa9-11ea-80c4-1afbae86eebe.png">

Only happens when first nav item is selected.

**Comment by zoltanszogyenyi** [comment]
Hey @jashsayani,

Thanks for the info. We'll get this fixed in the next release.

**Comment by zoltanszogyenyi** [comment]
@jashsayani fixed in version 1.2.0: https://github.com/themesberg/volt-bootstrap-5-dashboard/releases/tag/v1.2.0
