### ISSUE TITLE
Footer breaks with Bootstrap v5.0.0-alpha2

### ISSUE THREAD

**Issue by ericfowler303** [themesberg/volt-bootstrap-5-dashboard#16]
There is a change between alpha1 and alpha2 dealing with .row: https://github.com/twbs/bootstrap/pull/31439

This breaks the footer in it's current implementation, it seems to only take up half of the width. Like that pull request states, by adding an additional .flex-fill class to the row the footer goes back to it's proper state.

**Comment by zoltanszogyenyi** [comment]
@ericfowler303 Thanks for letting us know! We're preparing an update this month with a few new features and an update to Bootstrap 5 Alpha 2.

**Comment by zoltanszogyenyi** [comment]
@ericfowler303 fixed in version 1.2.0: https://github.com/themesberg/volt-bootstrap-5-dashboard/releases/tag/v1.2.0
