### ISSUE TITLE
Buggy mobile nav animation

### ISSUE THREAD

**Issue by sooxt98** [themesberg/volt-bootstrap-5-dashboard#17]
the mobile nav just flash out  without any animation after clicking the hamburger menu and it delays about 1 second, only the close button works fine

**Comment by zoltanszogyenyi** [comment]
Hey @sooxt98,

Thanks for letting me know. I'll add this to the list of things to be fixed for the next release with the Bootstrap v5 alpha-2 release.

**Comment by zoltanszogyenyi** [comment]
@sooxt98 fixed in v1.3

**Comment by sooxt98** [comment]
Hi devs, @zoltanszogyenyi i wonder why the mobile nav animation are completely removed?
