### ISSUE TITLE
Missing svg files

### ISSUE THREAD

**Issue by sauy7** [themesberg/volt-bootstrap-5-dashboard#18]
The following two places in the scss files refer to svg files that are missing from the img directory:

https://github.com/themesberg/volt-bootstrap-5-dashboard/blob/master/src/scss/volt/components/_shapes.scss#L10
https://github.com/themesberg/volt-bootstrap-5-dashboard/blob/master/src/scss/volt/components/_shapes.scss#L33

**Comment by zoltanszogyenyi** [comment]
Thanks, @sauy7 for letting me know! I'll get this fixed in the next release.

**Comment by zoltanszogyenyi** [comment]
@sauy7 fixed in version 1.2.0: https://github.com/themesberg/volt-bootstrap-5-dashboard/releases/tag/v1.2.0
