### ISSUE TITLE
Some form inputs lack focus effect

### ISSUE THREAD

**Issue by jmsche** [themesberg/volt-bootstrap-5-dashboard#23]
As the title says, some form inputs lack a focus effect.

See on this page: https://demo.themesberg.com/volt/pages/components/forms.html

Items without a focus effect:

* icon left
* icon right
* password
* birthday

**Comment by jmsche** [comment]
Same applies to Pro version: https://demo.themesberg.com/volt-pro/pages/components/forms.html

But with these two additional inputs:

* select state
* select states

**Comment by zoltanszogyenyi** [comment]
Thanks, @jmsche for pointing these out. I'll make sure we address the input state issues in the next update for version 1.3.

**Comment by zoltanszogyenyi** [comment]
@jmsche fixed in version 1.3.0.
