### ISSUE TITLE
Update to Bootstrap 5 Beta 1

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/volt-bootstrap-5-dashboard#24]
[Bootstrap 5 Alpha 3 has been launched](https://themesberg.com/blog/bootstrap/bootstrap-5-alpha-3) with improvements regarding the accordion, input elements, and some additions to the utility API.

**Comment by ericfowler303** [comment]
May as well skip to Beta 1: https://blog.getbootstrap.com/2020/12/07/bootstrap-5-beta-1/

**Comment by zoltanszogyenyi** [comment]
@ericfowler303, yea, that's right. They have released it quite rapidly. We're excited to bring RTL support to Volt!

**Comment by slavus** [comment]
Any plans to bring boostrap 5 Beta 1 support

**Comment by zoltanszogyenyi** [comment]
@slavus already done, we need a few days to test it out and then we'll make a release

**Comment by zoltanszogyenyi** [comment]
@slavus the pro version has been updated, tomorrow we'll update the open-source one. You can check it out for a preview: https://demo.themesberg.com/volt-pro/index.html to know what to expect

**Comment by mustafa-online** [comment]
@zoltanszogyenyi This [changelog](https://themesberg.com/docs/volt-bootstrap-5-dashboard/getting-started/changelog/)  is not updated, how to check the new additions?

**Comment by zoltanszogyenyi** [comment]
@mustafa-online here https://themesberg.com/product/admin-dashboard/volt-premium-bootstrap-5-dashboard#changelog we'll update the docs soon too with the new components from beta 1

**Comment by zoltanszogyenyi** [comment]
@ericfowler303 @slavus @mustafa-online v1.3.0 is now based on Bootstrap Beta 1 https://github.com/themesberg/volt-bootstrap-5-dashboard/releases/tag/v1.3.0

**Comment by mustafa-online** [comment]
@zoltanszogyenyi , Thanks a lot.
Any plans for RTL support?
