### ISSUE TITLE
Bootstrap 4 support, sidebar collapsing

### ISSUE THREAD

**Issue by nikhil2209** [themesberg/volt-bootstrap-5-dashboard#25]
Are there any estimates as to when bootstrap 4.5 compatibility will be released?

Also, a new feature request - could the sidebar be made collapsible?

**Comment by ericfowler303** [comment]
This template is made specifically for Bootstrap 5 since it's such a radical departure from previous versions. I wouldn't count on that happening but I don't work for Themesburg to ultimately know.

**Comment by zoltanszogyenyi** [comment]
@nikhil2209 @ericfowler303 we have a Bootstrap 4.5 version ready, I'll add a separate branch for it - but it will not be updated in the future

@ericfowler303 you're right to say that Volt has been built to be supported and updated primarily for the Bootstrap 5 version. We are ready to bring an update for Bootstrap 5 Beta and with that, support for RTL.

**Comment by zoltanszogyenyi** [comment]
The sidebar collapse is supported in the [pro version](https://demo.themesberg.com/volt-pro/).
