### ISSUE TITLE
Volt PRO v1.2.0 - Navigation errors on mouse over

### ISSUE THREAD

**Issue by app-generator** [themesberg/volt-bootstrap-5-dashboard#30]
By accessing any page on `mouse over` on the navigation menu, errors are bumping in the JS console. 

1. Start the template
2. Open the JS console
3. Navigate to `dashboard.html`
4. Perform `mouse over` action on the navigation menu 
4. See errors in the JS console

```javascript
Uncaught TypeError: Cannot read property 'nextElementSibling' of null
    at Object.next (bootstrap.min.js:6)
    at t.e._getMenuElement (bootstrap.min.js:6)
    at new t (bootstrap.min.js:6)
    at HTMLLIElement.<anonymous> (volt.js:62
```

Expected behavior
Access `dashboard.html` and visualize the content without errors.

Screenshots
![volt-pro-mouseover-error](https://user-images.githubusercontent.com/51070104/105135729-2fc92500-5af9-11eb-9b5b-2ca6053aa8b3.gif)

Environment:
 - OS: Windows
 - Browser Chrome (latest)

**Comment by zoltanszogyenyi** [comment]
Fixed in v1.3.
