### ISSUE TITLE
Bump to bootstrap 5 beta 2

### ISSUE THREAD

**Issue by tacman** [themesberg/volt-bootstrap-5-dashboard#39]
https://blog.getbootstrap.com/2021/02/10/bootstrap-5-beta-2/

In particular, some things have changed with dropdowns.  Can you please update?

Thx.

**Comment by zoltanszogyenyi** [comment]
@tacman next week

**Comment by sfajardo2016** [comment]
> @tacman next week

So more than 2 months and no updates, guess will avoid it like plague.

**Comment by zoltanszogyenyi** [comment]
@tacman we're releasing an update today to the stable version of Bootstrap 5 and quite a few more updates regarding styling and components.
