### ISSUE TITLE
[Pro version] Choices selects not rendered correctly

### ISSUE THREAD

**Issue by jmsche** [themesberg/volt-bootstrap-5-dashboard#48]
Hi,

I just noticed some issues on the Choices selects ("Select state" & "Select states" selectors on this demo page: https://demo.themesberg.com/volt-pro/pages/components/forms.html):

* No focus effect
* Not the same height as other inputs
* Labels' top & bottom margins are not the same as other labels, but that seems to be due to classes applied to the labels that are not applied to the others

**Comment by zoltanszogyenyi** [comment]
Hello @jmsche,

Thanks for reporting this. We will address this issue in the next update.

Cheers,
Zoltan
