### ISSUE TITLE
Sidebar gets caught in open/close loop

### ISSUE THREAD

**Issue by PerryCodes** [themesberg/volt-bootstrap-5-dashboard#49]
GitHub has a 10mb limit on files, so I tossed this on a Gdrive:
https://drive.google.com/file/d/12hSgoph1vvrjHUktcJn1H5eejAbe0xJz/view?usp=sharing

**Comment by zoltanszogyenyi** [comment]
Hey @PerryCodes,

Thanks for the video. Please specify your OS version and browser version. I tried to reproduce this on a Mac, didn't have this issue. I suspect this may be a Windows issue, so we'll need to provide a fix using the OS.

Thanks,
Zoltan

**Comment by zoltanszogyenyi** [comment]
@PerryCodes we'll address this issue tommorow

**Comment by PerryCodes** [comment]
Zoltán  -
So very good to hear!!  I think this is one of the best admin templates out there.  At first, I thought my project was going to use Angular, which doesn’t have this bug.  Same with the React/Vue/Laravel versions… no bug.

But now my project has switched to server-rendered plain ASP.NET Core… so have a Bootstrap template that can help my “not a designer syndrome” I’ve been suffering from… “Yes please” is what I say!!

If it were just the “opening/closing” that would be one thing… but once it goes into that state, you can see from this screenshot that things really get bad!  In this screenshot, I do not have my navsidebar set to “closed” and I’ve been hovering for several seconds with the mouse… yet the sidenavbar stays in a “closed” when it should not be.  This is not good!

Wish you much luck in finding a fix.  If I were better with CSS/JavaScript, I would have made an attempt and then send you a pull request… but I’m not very good – especially with more modern UI’s and development techniques - like this one!

Regards,
Jason P.

***@***.***

**Comment by zoltanszogyenyi** [comment]
@PerryCodes we've made a new release fixing the problem for Volt Pro. You can download the new version from the "downloads" section. It took use about 2 days to fix this, it was a pesky little bug, but we managed to fix it by rendering the JS for the sidebar before the animation would happen from expanded to contracted.

**Comment by PerryCodes** [comment]
Good news.  Though it's been about 18 hours and I still see version 1.4.1 in downloads and no related changes  to the code here.  You still working on getting it ready?

**Comment by zoltanszogyenyi** [comment]
Hey @PerryCodes,

We encountered a problem after adding Webpack to Volt (another feature that we have added now) and we worked on that yesterday. I hope that today we can make a safe and stable release :)

**Comment by PerryCodes** [comment]
I could report this... don't think I would have been able to find the fix.  Very nice job!
