### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/volt-bootstrap-5-dashboard#6]
RTL support.

**Comment by AbdQaadir** [comment]
Hello, @zoltanszogyenyi 

I'd like to work on the issue raised here. This would be a great opportunity to contribute to open source and improve my skills.

**Comment by zoltanszogyenyi** [comment]
Hey @AbdQaadir,

That would be awesome! I think you also know Arabic, right? That would make it easier.

The way I suggest going forward is like this:

The RTL version should be built in a way that it is an extension of the current Sass files. I think we could create a "_rtl.scss" file and override certain Bootstrap 5 variables and custom classes (if needed, BS5 variables have priority) to make text, elements, sidebars, and so on be aligned in a proper way.

Would you prefer me to prepare the structure of these files and the methodologies or would you like to start right away?

Ultimately it will become a sidebar element called "RTL version" and when clicked on it it will show the dashboard with RTL support.

Thanks for your contribution!

**Comment by AbdQaadir** [comment]
Yeah, I know a bit of Arabic.

I'd prefer you prepare the structure and methodologies.

**Comment by zoltanszogyenyi** [comment]
I'll let you know when it is ready then!

**Comment by zoltanszogyenyi** [comment]
[Bootstrap 5 Beta 1](https://themesberg.com/blog/bootstrap/bootstrap-5-beta) now brings official support for RTL, so this issue will be merged with this one: https://github.com/themesberg/volt-bootstrap-5-dashboard/issues/24
