### ISSUE TITLE
More advanced components?

### ISSUE THREAD

**Issue by aadrian** [themesberg/volt-bootstrap-5-dashboard#7]
Any plans supporting more advanced components (even if only for the pro version)?
e.g. jstree, date range picker, select2

**Comment by zoltanszogyenyi** [comment]
Hey @aadrian,

**Js Tree** - I'll check it out and consider it for v1.1
**Date Range Picker** - We actually planned on shipping it, but we'll keep it for the next version
**Select2** - This is a jQuery dependent plugin. We used Choices.js which is vanilla JS. Check it out here: https://demo.themesberg.com/volt-pro/pages/components/forms.html

Regarding Select2, we will launch Volt with Bootstrap v4.5 (stable version) which is built using jQuery. We used Select2 there.

**Comment by aadrian** [comment]
@zoltanszogyenyi Choices.js still does not seem to have all the features Select2 has, and also seems to abandoned pretty quickly (select2 is very old for a JS library and still kicking) .

**Comment by zoltanszogyenyi** [comment]
You'll be able to use Select2 with Volt's Bootstrap v4.5 version. It's impossible to use Select2 with Volt + Bootstrap 5 because we decided to keep it vanilla JS.

**Comment by aadrian** [comment]
> I would love to see Select2 get a vanilla JS version too.

There's a jQuery free branch https://github.com/select2/select2/tree/select2-5.x , but it's not released yet.

> Alternatively, you can require jQuery + Select2 from Volt BS4.5 into Volt with BS5 as well if you'd like.

Great, thanks!

**Comment by zoltanszogyenyi** [comment]
That is definitely going on my watch list then! Thanks for the interest.

**Comment by aadrian** [comment]
> You'll be able to use Select2 with Volt's Bootstrap v4.5 version.

@zoltanszogyenyi  Any estimate for v4.5 ?

The biggest drawback of TWBS 5 seems to be the missing IE 10/11 support :( . 
Unfortunately this will make it totally unusable for most corporate environments  :( .

**Comment by zoltanszogyenyi** [comment]
@aadrian we'll try to roll it out by the end of this week/start of next week. It is 95% done in fact, but still, need to do some work on the online documentation. I'll let you know here!

**Comment by aadrian** [comment]
> we'll try to roll it out by the end of this week/start of next week.

@zoltanszogyenyi sounds good, thank you.

**Comment by mustafa-online** [comment]
**Repeater Field** would be great!

**Comment by zoltanszogyenyi** [comment]
We're releasing v1.4.0 today with an update to the stable version of Bootstrap 5 and an upgraded layout and newly styled components.
